name: central_vol_app
description: A Flutter project for Central Volunteering
publish_to: "none" 

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  font_awesome_flutter: ^10.7.0
  google_maps_flutter: ^2.5.0
  google_maps_flutter_web: ^0.5.4
  provider: ^6.1.1
  js: ^0.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/ResQNet.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/ResQNet.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
