// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqexrM4flBu8VmPUKtOxDimUVuALKgB_k',
    appId: '1:950746643547:web:697ed5c4d58069b0b1d37e',
    messagingSenderId: '950746643547',
    projectId: 'central-vol-app',
    authDomain: 'central-vol-app.firebaseapp.com',
    storageBucket: 'central-vol-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBySbNW8yn9q14ngiHbKMo3Lj1QnOctAy0',
    appId: '1:950746643547:android:257b2ff0abddc344b1d37e',
    messagingSenderId: '950746643547',
    projectId: 'central-vol-app',
    storageBucket: 'central-vol-app.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCIwnhDa1TUhNTcGA1tIL8tfxdomwnOaA',
    appId: '1:950746643547:ios:cdf597267c710391b1d37e',
    messagingSenderId: '950746643547',
    projectId: 'central-vol-app',
    storageBucket: 'central-vol-app.firebasestorage.app',
    iosBundleId: 'com.example.centralVolApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqexrM4flBu8VmPUKtOxDimUVuALKgB_k',
    appId: '1:950746643547:web:fb564fb18a2b5a6fb1d37e',
    messagingSenderId: '950746643547',
    projectId: 'central-vol-app',
    authDomain: 'central-vol-app.firebaseapp.com',
    storageBucket: 'central-vol-app.firebasestorage.app',
  );

}